### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by vr8hub**
I've never read these, so I had (wanted) to read the first one before I proofed the second one. This fixes several issues I found:
1. Several French phrases that are in Merriam-Webster were italicized.
2. A couple that should have been weren't.*
3. Some song lyrics that were blockquoted in the scans weren't in the production.
4. The letter footer CSS was missing, so a signature wasn't right-justified.
5. Some sounds weren't italicized.
6. Standardized the "Day Dream" ship name to "Daydream" (per our conversation on the list).
7. Some of the dedication CSS was missing.
8. Couple of other minor typos and/or spelling updates.

*The word "citoyen" is only italicized once. It's tagged with spans the remaining time; I assume this is due to the "distracting to the reader" exception, although I personally didn't think it occurred enough to distract. I left it alone, though.

### CODE REVIEW

**Comment by acabal** [comment]
Excellent, thanks. Re. citoyen, we can make it consistent and italicize all instances if it doesn't occur incredibly frequently. Can you do that?

**Comment by vr8hub** [comment]
I can. I hadn't looked at the production notes—it does specifically mention not italicizing them.

I should say that I don't find italicized foreign words distracting. Since I'm not sure where your "incredibly frequently" line is drawn, here are the numbers: citoyen or citoyenne occurs around 90 times in total. However, they tend to go in clumps: they're in only 13 of the 31 chapters, and two-thirds of them are in 4 chapters. Even for the most populous chapter (18 in chapter 30), there are usually at most a couple on a page, with one exception where there are 6. There are three or four more pages where there are 4. So, out of 250'ish pages, there are less than 10 where there are more than a couple, and the vast majority have none. I don't consider that "incredibly frequently," but you're the final arbiter.

Also, there are also instances where it is used as a title (capitalized Citoyen, e.g. "Citoyen Bibot"; those weren't tagged (per our title policy), and I'm going to leave them alone as well. These were not included in the above numbers since they won't be italicized.

I have the changes made, including removing the production note. I'll check them in if you're OK with the above.

**Comment by vr8hub** [comment]
I should have said: this is on an iPad-sized screen reading double-columned landscape, where each column is a page. It's roughly 125% or so of the content (words) of a book page.

**Comment by acabal** [comment]
OK. If they're that concentrated then I'd say it's probably distracting. What we should do instead is just mark them up with `<span xml:lang="fr">`. If we change our minds later we can easily replace them. And, of course we should do the same for the following novels.

**Comment by vr8hub** [comment]
No problem. They were already tagged, so this should be ready to go.

**Comment by acabal** [comment]
Thanks!

**Pull request merged**
